### ISSUE TITLE
Test GET requests for invalid dataset id

### ISSUE THREAD

**Issue by jamie-ralph** [josephlewisjgl/statswalespy#3]
statswalesr implementation (ua = user agent)

request <- httr::GET(url, ua)

  if (httr::http_error(request)) {

    message("Dataset was not found. Check your dataset id for typos. If your dataset id is correct, the API might be unavailable.")

    return(NULL)

  }
  else {
    message("Downloading StatsWales dataset...")
  }

**Comment by josephlewisjgl** [comment]
Tried changing the try/except in the function from a ValueError to a HTTP error and the function can't handle that! Will wait to have another look some time in the week. The best way to do the internet connection bit is definitely requests and I will add that in myself this week I think.

**Comment by jamie-ralph** [comment]
I've put the HTTP error handling in my functions if that helps :)
