### ISSUE TITLE
Set up unit tests

### ISSUE THREAD

**Issue by jamie-ralph** [josephlewisjgl/statswalespy#4]

**Comment by josephlewisjgl** [comment]
Unit tests added for first function. I checked for everything you tested for in R and passed the four after adding in some error handling for int and list id's I just check for strings and prompt a user to enter the value as a single string. I'll try adding the tests for searching in the next week. Now that I understand how it works I should be able to whip up some tests a lot faster if we discuss what else we could test for in our next catch up. Maybe a way to test the check connection?

**Comment by josephlewisjgl** [comment]
Test added for search. Integers pull up an error i think we may need to add something similar to what I added in my function. I'll wait to have a chat before I change it.
